### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by Boomatisch** [Mooreiche/AIBackup#3]
Hello there. I'll test your Script soon. If i can improve it, can i re-release it then? I will Credit you and put your Link in there

Friendly Regards
Boomatisch

**Comment by Mooreiche** [comment]
Hey there! Yeah sure you can!!! 

It would be nice to be in the credits - thx. have fun improving it


Greetings from Germany

**Comment by Boomatisch** [comment]
Danke! Grüße zurück aus Deutschland :D

**Comment by Boomatisch** [comment]
Can you send me your Discord or something like that? I want to Show you what i just did 


_EDIT_
or add me on Discord. 

Boomatisch | David#2292
